name: Publish to RubyGems

on:
  repository_dispatch:
    types: [publish]

jobs:
  publish:
    name: Publish to RubyGems
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - run: |-
          git clone ${{ github.event.client_payload.repository }} \
            --branch ${{ github.event.client_payload.ref }} \
            --depth 1 \
            .
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          rubygems: latest
      - uses: rubygems/release-gem@v1
